### ISSUE TITLE
Null-Reference Exception on first build

### ISSUE THREAD

**Issue by UNeaK1502** [kletellier/Arduino-Assetto-Corsa-Dashboard#1]
Hey there,
first of all, thank you a lot for your work here.

When I try to build the program for the first time, the compiler throws an exception in the cUtils.cs.
Since my coding skills are rather basic I can't figure out what's wrong here, see the image attached.
I'm using VS2022. I hope you still read the answers here :P 

Thank you!
![image](https://user-images.githubusercontent.com/98899981/221039170-5547e51a-de43-4651-9dd0-6ecbb5fa7e2b.png)

**Comment by kletellier** [comment]
Hi,
Thank you for using it, you've have this issue by running , not on building ? I think your COM port array contains one element without the name key, i'm trying to push a fix

**Comment by UNeaK1502** [comment]
Hi, thank you for your quick reply. I actually managed to fix it with ChatGPT and stumbled upon another error.
Github doesnt let me format the code properly, sorry for that
Fix for cUtils
class GetCOMPort():

> foreach (ManagementObject mObj in mReturn)
> {
>     if (mObj["Name"] == null)
>     {
>         continue;
>     }
>     
>     if (mObj["Name"].ToString().ToLower().Contains("arduino") || mObj["Name"].ToString().ToLower().Contains("ch340"))
>     {
>         // rest of the code
>     }
> }

Fix for AssettoCorsa.cs
class OnGraphicsUpdated():

>         public virtual void OnGraphicsUpdated(GraphicsEventArgs e)
>         {
>             
>             if (GraphicsUpdated != null)
>             {
>                 GraphicsUpdated(this, e);
> 
>                 if (e.Graphics.Status != null)
>                 {
>                     try
>                     {
>                         if (gameStatus != e.Graphics.Status)
>                         {
>                             gameStatus = e.Graphics.Status;
> 
>                             if (GameStatusChanged != null)
>                             {
>                                 GameStatusChanged(this, new GameStatusEventArgs(gameStatus));
>                             }
>                         }
>                     }
>                     catch (Exception ex)
>                     {
>                         // handle the exception appropriately
>                     }
>                 }
>             }
>         }

Again, I don't actually know why its not working, but now it is working for me atleast. Thank you again!

**Comment by kletellier** [comment]
solved
