### ISSUE TITLE
Launching server

### ISSUE THREAD

**Issue by 1sayosa** [kletellier/Arduino-Assetto-Corsa-Dashboard#2]
what do you mean by Launch your server in Server\AC_Arduino\Bin ?
Do i need to have a ac online server and put a server in the bin ?
Bit confused here

**Comment by kletellier** [comment]
no the server are the binary compiled in the  server folder  Server\AC_Arduino\Bin (Ac_arduino.exe)

**Comment by 1sayosa** [comment]
Where is the Bin ? 
![image_2024-04-29_165221294](https://github.com/kletellier/Arduino-Assetto-Corsa-Dashboard/assets/168435961/3e521df7-4d28-4ad4-b606-2ec634e204bb)
installation just wasnt really clear for me

**Comment by kletellier** [comment]
you've to compile it with visual studio (min version vs 2019) and after you've a bin folder with debug or release subfolder according to your compilation mode where you can find the binary
